#! /bin/bash

# piPipes, a set of pipelines for PIWI-interacting RNA (piRNA) and transposon analysis
# Copyright (C) 2014-2016  Bo Han, Wei Wang, Zhiping Weng, Phillip Zamore
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# https://github.com/bowhan/piPipes.git
# A pipeline collection for piRNA and transposon analysis
# from small RNA seq, RNA-seq, CAGE/Degradome/RACE-seq, ChIP-seq and Genomic-seq
# Wei Wang
# Bo W Han
# the Zamore lab and the Weng lab
# Howard Hughes Medical Institute
# RNA Therapeutics Institute
# University of Massachusetts Medical School

declare -xr PACKAGE_NAME="piPipes"
declare -xr PROG_MAJOR_VERSION=2
declare -xr PROG_MINOR_VERSION=0
declare -xr PROG_PATCH_VERSION=0
declare -xr PROG_VERSION=${PROG_MAJOR_VERSION}.${PROG_MINOR_VERSION}.${PROG_PATCH_VERSION}

set -e -o pipefail
cmd=$(basename $0)
dir=$(dirname $(readlink -f $0))
if [[ "${cmd}" == "piPipes_debug" ]]; then set -x; fi
export SHELLOPTS
$dir/piPipes.sh "$@"
