#! /bin/bash
# pipipe 
# https://github.com/bowhan/pipipe.git
# An integrated pipeline for piRNA and transposon analysis 
# from small RNA Seq, RNASeq, CAGE/Degradome/RACE, ChIP-Seq and Genomic-Seq
# Wei Wang (wei.wang2@umassmed.edu)
# Bo W Han (bo.han@umassmed.edu, bowhan@me.com)
# the Zamore lab and the Weng lab
# Howard Hughes Medical Institute
# RNA Therapeutics Institute
# University of Massachusetts Medical School

##########
# Config #
##########
# formating
export COLOR_RED="\e[31;40m"; export  COLOR_GREEN="\e[32;40m"; export  COLOR_YELLOW="\e[33;40m"; export  COLOR_BLUE="\e[34;40m"; export  COLOR_MAGENTA="\e[35;40m"; export  COLOR_CYAN="\e[36;40m"; export COLOR_RED_BOLD="\e[31;1m"; export COLOR_RED_LIGHT="\e[91m"; export COLOR_GREEN_BOLD="\e[32;1m"; export COLOR_GREEN_LIGHT="\e[92m"; export  COLOR_YELLOW_BOLD="\e[33;1m"; export  COLOR_BLUE_BOLD="\e[34;1m"; export  COLOR_MAGENTA_BOLD="\e[35;1m"; export  COLOR_CYAN_BOLD="\e[36;1m"; export COLOR_END="\e[0m"; 
export RESET=`echo -ne '\e[0m'`; export BOLD=`echo -ne '\e[1m'`; export UNDERLINE=`echo -ne '\e[4m'`; export BLINK=`echo -ne '\e[5m'`; 
export SMALLRNA_COLOR=`echo -ne $COLOR_RED`; export RNASEQ_COLOR=`echo -ne $COLOR_GREEN`; export DEG_COLOR=`echo -ne $COLOR_YELLOW`; export CHIP_COLOR=`echo -ne $COLOR_MAGENTA`; export GENOME_COLOR=`echo -ne $COLOR_CYAN`; 
export COMMENT=`echo -ne $COLOR_BLUE`; export REQUIRED=`echo -ne $COLOR_RED_LIGHT`;  export OPTIONAL=`echo -ne $COLOR_GREEN_LIGHT`
export PACKAGE_NAME="pipipe"
export CONTACT_EMAILS=${UNDERLINE}"wei.wang2@umassmed.edu, bo.han@umassmed.edu"$RESET
export PIPELINE_DIRECTORY=$(dirname `readlink -f $0`)
export PATH=${PIPELINE_DIRECTORY}/bin:$PATH
. $PIPELINE_DIRECTORY/bin/pipipe_bash_functions

################
# DEBUG switch #
################
export DEBUG='-x'

#########
# Intro #
#########
export PIPIPE_INTRO='
Integrated, shell based pipeline collections for piRNA/transposon analysis of small RNA-Seq, RNA-Seq,
Degradome/RACE/CAGE-Seq, ChIP-Seq and Genomic-Seq. 

pipipe is generic with respect to the genomes it supports. Please visit our github website 
<github.com/bowhan/pipipe.git> for more information. 
Most of the pipelines offer two modes: 
1. Single library mode performs the mapping and analysis on a single library. 
2. Dual library mode performs pair-wise comparision between two libraries, using the outputs from 
single library mode.
'

export INSTALL_USAGE='
install
=======
Due to the limitation on the size of files by github, pipipe does not ship with all of the genome
sequences and annotation. Thus we provide this pipeline to download genome assemly files
from illumina iGenome project. Please make sure internet is available during this process. 
This pipeline will also install R packages that are unavaiable in your current system.
Use -D option to separate downloading and reference indexing. 
'

export SMALLRNA_INTRO=$SMALLRNA_COLOR'
small: small RNA pipeline, single library mode
==============================================
small RNA library typically clones 18–40nt small RNAs, including miRNA, siRNA
and piRNA. This pipeline maps those reads to rRNA, microRNA hairpin, genome, repbase annotated 
transposons, piRNA clusters with bowtie and uses bedtools to assign them to different annotations.
For each feature, length distrition, seqlogo, ping-pong score, et al,.  are calculated and graphed.
'

export SMALLRNA2_INTRO=$SMALLRNA_COLOR'
small: small RNA pipeline, dual library mode
============================================
This pipelines takes the output directories of the single library mode pipeline and do pair-wise
comparision between the two samples on microRNAs and piRNAs. Six different normalization methods
are provided. 
'

export RNASEQ_INTRO=$RNASEQ_COLOR'
rnaseq: RNASeq pipeline, single library mode
============================================
RNASeq pipeline was developped for dUTR based RNASeq method. It uses bowtie2 to align paired-end
reads to rRNA and STAR to align the unmapped reads to genome; Then it uses cufflinks for
quantification. It also directly align reads to transcriptome, repbase annotated transposon, piRNA
clusters using BWA-MEM. Quantification was done using eXpress. Basic statistics and graphs will be
given.
'

export RNASEQ2_INTRO=$RNASEQ_COLOR'
rnaseq: RNASeq pipeline, dual library mode
==========================================
This pipelines takes the output directory of the single library mode pipeline and do pair-wise
comparision between the two samples. 
'

export CAGE_DEG_INTRO=$DEG_COLOR'
cage/deg: CAGE & Degradome pipeline
===================================
Both types of libraries are designed to gather the information of the five prime end of RNAs CAGE
clones RNAs with Cap and Degradome clones RNAs with five prime monophosphate. The pipeline will
aligns paired end reads to rRNA with bowtie2, genome using STAR. Different from RNASeq, this
pipeline emphasizes on the accuracy of the five prime ends.
'

export CHIP_INTRO=$CHIP_COLOR'
chip: ChIP-Seq pipeline, single library mode
============================================
ChIP Seq pipeline aligns the paired-end to genome with BWA-MEM. Peak calling was done using MASC2. 
Then the control (Input) and the treated (IP) were compared using MACS2 with three different methods:
Poisson Pvalue, log10 fold enrichment, log10 likelihood between ChIP-enriched model and open 
chromatin model. Please refer to MACS2 manual for more details. The output bedGraph/bigWig is used
to draw metagene plot using bwtool in three different ways: (1) N nucleotides up/downstream of the 
5 prime end of each genomic feature; (2) N nucleotides up/downstream of the 3 prime end of each genomic 
feature;  (3) the whole body of each genomic feature been scaled with the same extension. 
'

export CHIP2_INTRO=$CHIP_COLOR'
chip: ChIP-Seq pipeline, dual library mode
==========================================
This pipelines takes the output directory of the single library mode pipeline and do pair-wise
comparision between the two samples. MACS2 bdgdiff is used. Since it requires no normalization, 
peak calling is redone without normalization. Same as the single library mode, meta gene plots
were drawn for each genomic features.
'

export GENOMIC_INTRO=$GENOME_COLOR'
dna: Genomic Seq pipeline
=========================
Genomic Seq pipelines aligns the paired-end reads to genome with Bowtie2, BWA-MEM and mrFast.
Variations, including transposon insertion and excision, were called using different algorithms,
including retroSeq and VariationHunter.
'

#########
# USAGE #
#########
usage () {
cat << EOF
======
$BLINK$BOLD$PACKAGE_NAME$RESET
======
$PIPIPE_INTRO
${UNDERLINE}usage${RESET}:

$COMMENT# to install genome and R packages in one step$RESET
$0	install -g dm3|mm9|hg19...	
$COMMENT# to only download the genome and install R packages (if the node is not appropriate to be used for building indexes); then run (1).$RESET
$0	install -g dm3|mm9|hg19 -D	
$COMMENT# to use iGenome that pipipe does not know (yet)$RESET
$0	install -g hg18 -l ftp://igenome:G3nom3s4u@ussd-ftp.illumina.com/Homo_sapiens/UCSC/hg18/Homo_sapiens_UCSC_hg18.tar.gz	

$COMMENT# run small RNA pipeline for fly sample, use 24 CPUs and output to out_dir$RESET
$SMALLRNA_COLOR$0	small -i input.trimmed.fq[.gz] -g dm3 -c 24 -o output_dir	
$COMMENT# run dual sample small RNA pipeline from small_rna_pipeline_output_dir1 and small_rna_pipeline_output_dir2 for dm3, use 24 CPUs, normalize to siRNA$RESET
$SMALLRNA_COLOR$0	small2	-a small_rna_pipeline_output_dir1 -b small_rna_pipeline_output_dir2 -g dm3 -c 8 -o output_dir -A wild-type -B mutant -N siRNA

$COMMENT# run RNASeq pipeline for mouse sample, dUTR based library$RESET
$RNASEQ_COLOR$0	rnaseq	-l left.fq -r right.fq -g mm9 -c 8 -o output_dir 
$COMMENT# run RNASeq pipeline for mouse sample, ligation based library$RESET
$RNASEQ_COLOR$0	rnaseq	-l left.fq -r right.fq -g mm9 -c 8 -o output_dir -L 
$COMMENT# run dual sample RNASeq pipeline for fly, sample name: w1 and piwi$RESET
$RNASEQ_COLOR$0	rnaseq2	-a rnaseq_pipeline_output_dir1 -b rnaseq_pipeline_output_dir2 -g dm3 -c 24 -A w1 -B piwi 

$COMMENT# run Degradome/CAGE-Seq for fly, under current working directory$RESET
$DEG_COLOR$0	deg -l left.fq -r right.fq -g dm3

$COMMENT# run ChIP-Seq pipeline for mouse sample, Narrow peak, like transcriptional factor, under current working directory$RESET
$CHIP_COLOR$0	chip -l left.IP.fq -r right.IP.fq -L left.INPUT.fq -R right.INPUT.fq -g mm9 -c 8 
$COMMENT# run ChIP-Seq pipeline for mouse sample, Broad peak, like H3K9me3, under current working directory$RESET
$CHIP_COLOR$0	chip -l left.IP.fq -r right.IP.fq -L left.INPUT.fq -R right.INPUT.fq -g mm9 -c 8 -B
$COMMENT# run ChIP-Seq pipeline for mouse sample, only use unique mappers (otherwise Bowtie2 randomly choose one best alignment for each read)$RESET
$CHIP_COLOR$0	chip -l left.IP.fq -r right.IP.fq -L left.INPUT.fq -R right.INPUT.fq -g mm9 -c 8 -Q 10
$COMMENT# to run ChIP Seq library in dual library mode, extend 2000bp for TSS/TES/meta analysis, name two samples w1 and piwi respectively$RESET
$CHIP_COLOR$0	chip2 -a chipseq_pipeline_output_dir1 -b chipseq_pipeline_output_dir2 -g mm9 -x 2000 -A w1 -B piwi

$COMMENT# run Genome Seq library, set VCF filtering depth to 500 (passed to "vcfutils.pl varFilter -D" and "retroseq.pl -call -depth")$RESET
$GENOME_COLOR$0	dna -l left.fq -r right.fq -g dm3 -d 500
${RESET}

Please email $CONTACT_EMAILS for any questions, suggestions or bugs. 
Thank you for using it. 

EOF
echo -ne ${COLOR_END}
}

#######
# Run #
#######
if [ $# -lt 1 ]; then usage; exit 1; fi
PROGRAM=`echo ${1} | tr '[A-Z]' '[a-z]'`
case $PROGRAM in
i|install)
	shift && bash $DEBUG pipipe_install_genomes.sh "$@" ;; # genome installation pipeline
s|small|smallrna|smallrna-seq|sra)
	shift && bash $DEBUG pipipe_smallRNA.sh "$@" ;; # small RNA pipeline, single library mode
s2|small2|smallrna2|smallrna-seq2|sra2)
	shift && bash $DEBUG pipipe_smallRNA2.sh "$@" ;; # small RNA pipeline, dual library mode
r|rnaseq|rna-seq|rsq|rna)
	shift && bash $DEBUG pipipe_RNASeq.sh "$@" ;; # RNASeq pipeline, single library mode
r2|rnaseq2|rna-seq2|rsq2|rna2)
	shift && bash $DEBUG pipipe_RNASeq2.sh "$@" ;; # RNASeq pipeline, dual library mode
d|deg|degseq|deg-seq|degradome|race|cage|cage-seq|cageseq)
	shift && bash $DEBUG pipipe_DegradomeSeq.sh "$@" ;; # degradome/CAGE/RACE pipeline
c|chip|chipseq|chip-seq)
	shift && bash $DEBUG pipipe_ChIPSeq.sh "$@" ;; # ChIP-Seq pipeline, single library mode
c2|chip2|chipseq2|chip-seq2)
	shift && bash $DEBUG pipipe_ChIPSeq2.sh "$@" ;; # ChIP-Seq pipeline, dual library mode
g|genomic|genome|genome-seq|genomeseq|dna|dnaseq|dna-seq)
	shift && bash $DEBUG pipipe_GenomeSeq.sh "$@" ;; # Genome-Seq library
*)
	echo2 "unrecognized option \"${1}\"! \nplease type \"${PACKAGE_NAME}\" without options to see usage." "error" ;;
esac






